---
- hosts: all
  become: true 
  vars:
    motd: Ansible Managed Node by Dnzl
  tasks:

  - name: Banner MOTD
    ansible.builtin.debug:
      msg: "{{ motd }}" 

  - name: install latest python3 and pip3 
    package:
      name: 
        - python3
        - python3-pip
      state: latest
      update_cache: yes

  - name: make pip3 as default pip ubuntu
    become: yes
    command: ln -sf /usr/bin/pip3 /usr/bin/pip
    when: ansible_distribution == 'Ubuntu'

  - name: make pip3 as default pip CentOS
    become: yes
    command: ln -sf /usr/bin/pip3 /usr/bin/pip
    when: ansible_distribution == 'CentOS'

  - name: make python3 as default python ubuntu
    become: yes
    command: ln -sf /usr/bin/python3 /usr/bin/python
    when: ansible_distribution == 'Ubuntu'
  
  - name: make python3 as default python CentOS
    become: yes
    command: ln -sf /usr/bin/python3 /usr/bin/python
    when: ansible_distribution == 'CentOS'
    
  - name: install java open-jdk ubuntu
    apt:
      name: openjdk-17-jdk
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install java open-jdk CentOS
    dnf:
      name: java-17-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS' 
